# .github/workflows/ci.yml

name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Uninstall existing Bundler
        run: |
          gem uninstall bundler -a -x || true
      - name: Install Bundler
        run: |
          if [[ "${{ matrix.ruby-version }}" == "2.5" ]]; then
            gem install bundler -v "~> 2.3.27"
          elif [[ "${{ matrix.ruby-version }}" == "2.6" || "${{ matrix.ruby-version }}" == "2.7" ]]; then
            gem install bundler -v "~> 2.4.0"
          fi
      - name: Build and run tests
        env:
          COVERAGE: true
          TERM: xterm
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bundle exec rake test
